# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow will
# 1. Build Python Wheel Nightly Version
# 2. Upload to PyPI

name: Python Package Build and Release (nightly)

on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: '0 7 * * *'
      timezone: 'America/Los_Angeles'

jobs:
  build-nightly:
    name: Build and Release Python Wheel Nightly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Build Nightly Package
        run: |
          python tools/build_wheels.py --type nightly

      - name: Upload Nightly Wheel
        uses: actions/upload-artifact@v4
        with:
          name: ai-edge-eval-nightly-wheel
          path: dist/*.whl

  test-before-publish:
    needs: build-nightly
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    name: Test Install and Import ai-edge-eval-nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          python -m pip cache purge
          python -m pip install --upgrade pip

      - name: Download Nightly Wheel
        uses: actions/download-artifact@v4
        with:
          name: ai-edge-eval-nightly-wheel
          path: ./dist

      - name: Install ai-edge-eval-nightly
        run: |
          python -m pip install dist/*.whl

      - name: Import model_eval
        run: |
          python -c "import model_eval"

  publish-nightly:
    name: Publish to PyPI
    needs: test-before-publish
    runs-on: ubuntu-latest
    steps:
      - name: Download Nightly Wheel
        uses: actions/download-artifact@v4
        with:
          name: ai-edge-eval-nightly-wheel
          path: ./dist

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_UPLOAD_TOKEN }}
        run: uv publish dist/*.whl

  test-after-publish:
    needs: publish-nightly
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    name: Test Install and Import ai-edge-eval-nightly from PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          python -m pip cache purge
          python -m pip install --upgrade pip

      - name: Install ai-edge-eval-nightly from PyPI
        run: |
          python -m pip install ai-edge-eval-nightly

      - name: Import model_eval
        run: |
          python -c "import model_eval"
